export const SIGN_IN = "SIGN_IN";
export const SIGN_UP = "SIGN_UP";
export const SET_ERRORS = "SET_ERRORS";
export const SET_USER = "SET_USER";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const CREATE_IMAGE_URL_SUCCESSFUL = "CREATE_IMAGE_URL_SUCCESSFUL";
